
# ml4tTrain will automatically change the ENCUT, ML_RCUT, LANGEVIN_GAMMA 
# in INCAR and elements in nequIP.yaml according to elements in POSCAR.
# So only POSCAR in originDir and testDir need to be change in two different
# learning proccess.

# ml4tTrain config.yaml --runMode {all(default), ab or train} should run in main node to submit jobs.

# ml4tTest config.yaml --runMode {run(default) or get}. When enabling runMode=run, it should be submitted 
# to a computational node with vasp module loaded(Detailed in Testscript.sh). When enabling runMode=get, it can
# run under main node (because there's no any actual MD or DFT computation).



Sectors: 3  #number of sectors to shift
WorkDir: .  #Directory to work
originDir: ./origin   #Directory to store original INCAR and POSCAR for VASPMD.
POTCARDir: /home/apps/vasp6.3.0/potpaw_PBE    #Directory to store POTCARS
nThreads: 2   #How many job can be submitted at the same time.
attachDir: ./attach #Directory to store Learnscript, MDscript, nequIP.yaml and vdw kernal.
MDscript: MDscript.sh #name of MDscript.
username: jxliu #username
scriptLearn: Learnscript.sh #name of Learnscript.
testDir: ./test #Directory to store original INCAR and POSCAR(typically large angle tbm) for test.
minimizeDir: ./minimize
collectMinDat: True
collectFreq: 5
collectMode: AB